from rtmidi.midiconstants import *


# program values according to position on grid 
PROGRAM_BROWSE = 0
PROGRAM_ASSIGN = 5

PROGRAM_EDIT = 1

PROGRAM_SAVE_SONG = 2
PROGRAM_SAVE_SLICES = 6

PROGRAM_LOAD_SONG = 3
PROGRAM_LOAD_SLICES = 7

# map of program values according to chopogy 
PROGRAM_APP_VALUE = [0] * 8
PROGRAM_APP_VALUE[PROGRAM_BROWSE] = 1 
PROGRAM_APP_VALUE[PROGRAM_EDIT] = 2
PROGRAM_APP_VALUE[PROGRAM_ASSIGN] = 3
PROGRAM_APP_VALUE[PROGRAM_LOAD_SLICES] = 4
PROGRAM_APP_VALUE[PROGRAM_SAVE_SLICES] = 5
PROGRAM_APP_VALUE[PROGRAM_SAVE_SONG] = 6
PROGRAM_APP_VALUE[PROGRAM_LOAD_SONG] = 9


# Operational Codes 
FUNCTION = 0xC1
TOGGLE_CH_SEQ = 0xC2
PREV = 0xC3
NEXT = 0xC4
CH_SEQ_SELECT = 0xC5

# Codes match yamaha controller
TRIM_START = 0x4a
TRIM_END = 0x47
CHANGE_RATE = 0x72
CHANGE_PITCH = 0x13
CHANGE_TEMPO = 0x12
CHANGE_TEMPO_PITCH = 0x11
CHANGE_VOLUME = 0x48
CHANGE_PANNING = 0x49



GRID_SIZE = 16 

CTL_CLOCK_SPEED = 1200 # 0.05 sec


CONTROLS = [PROGRAM_CHANGE, PROGRAM_CHANGE, PROGRAM_CHANGE, PROGRAM_CHANGE,
            CH_SEQ_SELECT, CH_SEQ_SELECT, CH_SEQ_SELECT, CH_SEQ_SELECT,
            FUNCTION, TOGGLE_CH_SEQ, PREV, NEXT,
            CHANGE_RATE, CHANGE_TEMPO_PITCH,  TRIM_START, TRIM_END,
						NOTE_ON, NOTE_ON, NOTE_ON, NOTE_ON,
						NOTE_ON, NOTE_ON, NOTE_ON, NOTE_ON,
						NOTE_ON, NOTE_ON, NOTE_ON, NOTE_ON,
						NOTE_ON, NOTE_ON, NOTE_ON, NOTE_ON]


  

